### ISSUE TITLE
Create trash bin

### ISSUE THREAD

**Issue by SirVeggie** [ohtuprojekti-farmasia/farmasia-vr#104]
~~Problems with this commit 0d853ce2bc1943e85784be6a9b38768cdc623286~~

Commits: 0d853ce
2653afe
78e5ac4c03b9c0b352bdf75764e3a7af5c9fe434
82aa77c44154efbbf877d42a0f75a198da4f708f
693d65bd52f8ce301c877d6375e54a1f2587ef6a
5b6aec96d23db012930594fae6d79136a042801f (addresses previously mentioned problems)

- [x] Create basic model for a trash bin
- [x] Use Interactables DestroyInteractable() instead of MonoBehaviour.Destroy()
- [x] Destroy interactable items placed inside the trash bin (store on a list of placed items before destroying)
- [x] Create script for trash bin

----
Reviewer: Reko

**Comment by heidihas** [comment]
Other fixes done except
1) Floor script is not attached to floor prefab.
2) Is there any reason why the trash can is not on the parent object? You can use the script on the parent by subscribing to the triggers collisions using CollisionSubscription class.

**Comment by Mirex97** [comment]
Found a bug with GeneralItem that needs fixing in 0d853ce
