### ISSUE TITLE
Make sterilization pouch and sterile drape cover, disinfection cloth models

### ISSUE THREAD

**Issue by Reksa97** [ohtuprojekti-farmasia/farmasia-vr#162]
Commits: afe6be00b021b43208a4137be2bb5eb8e4d0f5bf
Reviewer: @heidihas 
Models from Metropolia are unusable so better ones have to be made

- [x] make models
- [x] add to Models
- [x] Improve Models to acceptable state
- [x] add to Prefabs/Models
- [x] add to Prefabs/Equipment

**Comment by heidihas** [comment]
Now it seems that the disinfecting cloth script has been added to a wrong object. While the object is an animated drape cover that stays static once opened in the laminar cabinet, the script refers to small cloths/tissues that are used for disinfecting the medicine bottle and then thrown away to the small trash bin in the laminar cabinet.
