### ISSUE TITLE
Add tests for progress system

### ISSUE THREAD

**Issue by porrasm** [ohtuprojekti-farmasia/farmasia-vr#52]
File: [ProgressManager.cs](https://github.com/ohtuprojekti-farmasia/farmasia-vr/blob/dev/Assets/Scripts/ProgressSystem/ProgressManager.cs)
Test: [ProgressManagerTest.cs](https://github.com/ohtuprojekti-farmasia/farmasia-vr/blob/dev/Assets/Tests/EditTests/ProgressManagerTest.cs)
Commits: 2322736d21ba73c92e3b8990f85d8005a5782893 c42fc835893033c67b79e77276750e35f83e6640 69123bdb2cc34f59d0d2fc4d81d72c86c9f0f3dc
- [x] Manager can add new tasks.
- [x] Manager can remove tasks.
- [x] Manager doesnt remove non removable tasks.
- [x] Tasks can Generate new tasks!
- [x] Manager creates finish task when empty activelist!

**Comment by doc97** [comment]
ProgressManagerTest.cs:
- Line 22, 30, 41: They all have different formatting of `count+/-1`, please fix
- Line 36: `TestTask task` is unused
- Line 35, 47, 58: `manager.ResetTasks(false);` should be redundant, if needed, move call to `AddTasks` in `ProgressManager` out of the constructor
- Line 53, 64: Remove Logger output

ProgressManager.cs:
- `testMode` variable is bad design, redesign class to better work with tests
